### ISSUE TITLE
Example code does not work

### ISSUE THREAD

**Issue by BarsikTheCaT** [kittykatattack/learningPixi#31]
`PIXI.loader
  .add("pictures/Mech1Walk.png")
  .load(setup);`
(why did author omit PIXI. prefix???)
`function setup() {
  var texture = PIXI.TextureCache["images/tileset.png"];

  var rectangle = new PIXI.Rectangle(1, 1, 64, 64);

  texture.frame = rectangle;

  var robot = new PIXI.Sprite(texture);

  robot.x = 100;

  robot.y = 100;

  stage.addChild(robot);

  renderer.render(stage);

}`

Gives me this error:
Uncaught DOMException: Failed to execute 'texImage2D' on 'WebGLRenderingContext': The cross-origin image at ... (path to my picture);

**Comment by evolveinua** [comment]
Because this manual - a piece of deprecated shit >_<
For example, i have a troubles with simple task - create triangle. And... Console told me "Graphics is not defined". All i need is a simple triangle. And this doesen't work! Hate-hate-hate.

**Comment by GoodBoyDigital** [comment]
HI @evolveinua , I can understand that you are frustrated but you must be careful not to direct it at the people who can help. This guide is great and has helped out many pixi users, you must remember that @kittykatattack has made this guide for free of his own back so really he owes us nothing. 

Instead it will be better to work together to figure out the issue and find a solution to your problem so that we can then share it with the community. If you can share your code I'm sure we can help to solve the issue.

Cheers

Mat

**Comment by lbpage** [comment]
i would suggest you use chrome dev editor [chrome dev editor](https://chrome.google.com/webstore/detail/chrome-dev-editor/pnoffddplpippgcfjdhbmhkofpnaalpg?utm_source=chrome-ntp-launcher) you can import your js test into this. As the tutorial says the pixi.js items require a webserver this is because the CORS policy blocks loading file resources directly from local storage reference [issue](https://github.com/Polymer/polymer/issues/1535)

**Comment by kittykatattack** [comment]
@evolveinua Yes, programming can be very frustrating! But we're here to help, so if you can break down your questions into smaller steps or provide us some examples of your course code, we'll do our best to help walk you through the problems you're having 😄.

**Comment by ickyrr** [comment]
Hi, @kittykatattack I'm the exact same problem. I'm still new to PIXI so I don't really understand the issue. Can you help me out? I only have the exact same code shown in the tutorial.

```
var stage = new PIXI.Container(),
    renderer = PIXI.autoDetectRenderer(256, 256);
document.body.appendChild(renderer.view);

//Use Pixi's built-in `loader` object to load an image
PIXI.loader
  .add("images/cat.png")
  .load(setup);

//This `setup` function will run when the image has loaded
function setup() {

  //Create the `cat` sprite from the texture
  var cat = new PIXI.Sprite(
    PIXI.loader.resources["images/cat.png"].texture
  );

  //Add the cat to the stage
  stage.addChild(cat);
  
  //Render the stage   
  renderer.render(stage);
}
```

Thanks!

**Comment by kittykatattack** [comment]
@ickyrr Hi! Are you running your code inside a web server?

**Comment by ickyrr** [comment]
@kittykatattack , yep, I was, previously. I was too tired I did not think of webpack dev server much sooner. It works now, thanks for the explanation above.

**Comment by kittykatattack** [comment]
Great news! 😄

**Comment by rajasekharsurineni** [comment]
@kittykatattack i am new to pixi and getting error Failed to execute 'texImage2D' on 'WebGLRenderingContext': The image element contains cross-origin data, and may not be loaded. while loading image .what i has to do
